-- AlterTable
ALTER TABLE "Batch" ALTER COLUMN "reopen_requested_date" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "reopen_approved_date" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "validated_date" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "matched_date" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "approved_date" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "nota_issued_date" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "branch_confirmed_date" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "paid_date" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "closed_date" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Bordero" ALTER COLUMN "reviewed_date" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "finalized_date" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Claim" ALTER COLUMN "tanggal_realisasi_kredit" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "dol" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "checked_date" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "doc_verified_date" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "invoiced_date" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "paid_date" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "review_date" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Contract" ALTER COLUMN "start_date" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "end_date" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "DebitCreditNote" ALTER COLUMN "drafted_date" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "reviewed_date" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "approved_date" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "acknowledged_date" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Debtor" ALTER COLUMN "tanggal_mulai_covering" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "tanggal_akhir_covering" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "tanggal_terima" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "tanggal_validasi" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "teller_premium_date" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Document" ALTER COLUMN "upload_date" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "expiry_date" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Invoice" ALTER COLUMN "due_date" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "MasterContract" ALTER COLUMN "coverage_start_date" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "coverage_end_date" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "effective_date" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "first_approved_date" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "second_approved_date" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Nota" ALTER COLUMN "issued_date" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "confirmed_date" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "paid_date" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Payment" ALTER COLUMN "payment_date" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "matched_date" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "PaymentIntent" ALTER COLUMN "planned_date" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Reconciliation" ALTER COLUMN "closed_date" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Record" ALTER COLUMN "accepted_date" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "rejected_date" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "SlaRule" ALTER COLUMN "last_triggered" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Subrogation" ALTER COLUMN "recovery_date" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "invoiced_date" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "closed_date" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "SystemConfig" ALTER COLUMN "effective_date" SET DATA TYPE TIMESTAMP(3);
